### Pandas

Pandad is a powerful data manipulation library in python, widely used for data anaysis and data cleaning. It provide two primary data structure -                                                                                               
**Series** - it is one dimensional array like object                                                                                                                                                                                           
**Dataframe** - it is a two dimensinal array like matrix(row and column)

In [2]:
import pandas as pd

### Series

In [4]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
## cRetae series from dictionary elemnt
data = {'a':1,'b':2,'c':3,'d':4}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
data = [10,20,30]
index= ['a','b','c']
series = pd.Series(data, index= index)
print(series)

a    10
b    20
c    30
dtype: int64

### DataFrame

In [9]:
## create a dataframe from a dictionary of list

data = {
    'Name':['neha','alice','siya'],
    'Age':[20,25,28],
    'City':['Bengalore', 'Newyork','Florida']

}

df= pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0   neha   20  Bengalore
1  alice   25    Newyork
2   siya   28    Florida
<class 'pandas.core.frame.DataFrame'>

In [11]:
## create a data frame from a list of dictionaries

data = [
    {'name':'krish', 'age':32,'City':'Bengalore'},
     {'name':'Nisraga', 'age':25,'City':'Bengalore'},
 {'name':'Nayan', 'age':32,'City':'Nagpur'}
]

df = pd.DataFrame(data)
print(df)

      name  age       City
0    krish   32  Bengalore
1  Nisraga   25  Bengalore
2    Nayan   32     Nagpur

In [13]:
## Read cv file with dagtaframe top 2 record

df = pd.read_csv('sales_data.csv')
print(df.head(2))

         Date Region  Product  Units_Sold  Unit_Price  Sales
0  2026-01-05  North   Laptop           5         750   3750
1  2026-01-08  South  Monitor           8         220   1760

In [14]:
##read bottom 2 record

print(df.tail(3))

          Date Region   Product  Units_Sold  Unit_Price  Sales
9   2026-03-10  South   Monitor          12         220   2640
10  2026-03-16   East  Keyboard          22          45    990
11  2026-03-23   West     Mouse          30          25    750

In [15]:
df

          Date Region   Product  Units_Sold  Unit_Price  Sales
0   2026-01-05  North    Laptop           5         750   3750
1   2026-01-08  South   Monitor           8         220   1760
2   2026-01-12   East  Keyboard          15          45    675
3   2026-01-18   West     Mouse          20          25    500
4   2026-02-03  North    Laptop           7         750   5250
5   2026-02-11  South   Monitor          10         220   2200
6   2026-02-17   East  Keyboard          18          45    810
7   2026-02-25   West     Mouse          25          25    625
8   2026-03-04  North    Laptop           6         750   4500
9   2026-03-10  South   Monitor          12         220   2640
10  2026-03-16   East  Keyboard          22          45    990
11  2026-03-23   West     Mouse          30          25    750

In [18]:
df['Date']

0     2026-01-05
1     2026-01-08
2     2026-01-12
3     2026-01-18
4     2026-02-03
5     2026-02-11
6     2026-02-17
7     2026-02-25
8     2026-03-04
9     2026-03-10
10    2026-03-16
11    2026-03-23
Name: Date, dtype: object

### Data Manipulation and nanalysis with pandas

### CSV FILE with Pandas

**pandas, the prefix pd.read_** is the universal key to loading almost any data file into a DataFrame (df).

In [20]:
df = pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselamani, Mr. Charles",male,NaN,0,0,2649,7.2250,NaN,C

**df.head()** is the most common command used to preview your data.df.head() will display the first 5 rows of your dataset.

In [22]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

**df.tail()** is the exact opposite of df.head(). It allows you to preview the very end of your DataFrame.
    calling df.tail() will display the last 5 rows of your dataset.

In [23]:
df.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.125,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.000,NaN,S
19,20,1,3,"Masselamani, Mr. Charles",male,NaN,0,0,2649,7.225,NaN,C

In [26]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

**df.describe()** is used to get a quick statistical summary of your dataset.
** it only analyzes numerical columns (integers and floats).

In [27]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,20.00000,20.000000,20.000000,17.000000,20.000000,20.000000,20.000000
mean,10.50000,0.500000,2.450000,28.000000,0.700000,0.500000,22.199370
std,5.91608,0.512989,0.825578,17.779904,1.080935,1.192079,18.058888
min,1.00000,0.000000,1.000000,2.000000,0.000000,0.000000,7.225000
25%,5.75000,0.000000,2.000000,14.000000,0.000000,0.000000,8.050000
50%,10.50000,0.500000,3.000000,27.000000,0.000000,0.000000,16.350000
75%,15.25000,1.000000,3.000000,38.000000,1.000000,0.250000,29.361450
max,20.00000,1.000000,3.000000,58.000000,4.000000,5.000000,71.283300

In [29]:
df[['Name','Sex','Ticket','Cabin','Embarked']]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
5,"Moran, Mr. James",male,330877,NaN,Q
6,"McCarthy, Mr. Timothy J",male,17463,E46,S
7,"Palsson, Master. Gosta Leonard",male,349909,NaN,S
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,347742,NaN,S
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,237736,NaN,C
10,"Sandstrom, Miss. Marguerite Rut",female,PP 9549,G6,S
11,"Bonnell, Miss. Elizabeth",female,113783,C103,S
12,"Saundercock, Mr. William Henry",male,A/5. 2151,NaN,S
13,"Andersson, Mr. Anders Johan",male,347082,NaN,S
14,"Vestrom, Miss. Hulda Amanda Adolfina",female,350406,NaN,S
15,"Hewlett, Mrs. (Mary D Kingcome)",female,248706,NaN,S
16,"Rice, Master. Eugene",male,382652,NaN,S
17,"Williams, Mr. Charles Eugene",male,244373,NaN,S
18,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,345763,NaN,S
19,"Masselamani, Mr. Charles",male,2649,NaN,C

In [30]:
df.dtypes =='object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [31]:
df.dtypes =='float'

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare            True
Cabin          False
Embarked       False
dtype: bool

In [32]:
df[df.dtypes[df.dtypes =='float'].index]

     Age     Fare
0   22.0   7.2500
1   38.0  71.2833
2   26.0   7.9250
3   35.0  53.1000
4   35.0   8.0500
5    NaN   8.4583
6   54.0  51.8625
7    2.0  21.0750
8   27.0  11.1333
9   14.0  30.0708
10   4.0  16.7000
11  58.0  26.5500
12  20.0   8.0500
13  39.0  31.2750
14  14.0   7.8542
15  55.0  16.0000
16   2.0  29.1250
17   NaN  13.0000
18  31.0  18.0000
19   NaN   7.2250

**df.columns** is an attribute used to view, inspect, or modify the column names of your DataFrame.

In [34]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [35]:
df[['Ticket']]

              Ticket
0          A/5 21171
1           PC 17599
2   STON/O2. 3101282
3             113803
4             373450
5             330877
6              17463
7             349909
8             347742
9             237736
10           PP 9549
11            113783
12         A/5. 2151
13            347082
14            350406
15            248706
16            382652
17            244373
18            345763
19              2649

In [36]:
df[['Ticket']][4:16]

       Ticket
4      373450
5      330877
6       17463
7      349909
8      347742
9      237736
10    PP 9549
11     113783
12  A/5. 2151
13     347082
14     350406
15     248706

In [37]:
df[['Ticket','Cabin']]

              Ticket Cabin
0          A/5 21171   NaN
1           PC 17599   C85
2   STON/O2. 3101282   NaN
3             113803  C123
4             373450   NaN
5             330877   NaN
6              17463   E46
7             349909   NaN
8             347742   NaN
9             237736   NaN
10           PP 9549    G6
11            113783  C103
12         A/5. 2151   NaN
13            347082   NaN
14            350406   NaN
15            248706   NaN
16            382652   NaN
17            244373   NaN
18            345763   NaN
19              2649   NaN

In [38]:
df[['Ticket','Cabin']][4:14]

       Ticket Cabin
4      373450   NaN
5      330877   NaN
6       17463   E46
7      349909   NaN
8      347742   NaN
9      237736   NaN
10    PP 9549    G6
11     113783  C103
12  A/5. 2151   NaN
13     347082   NaN

In [40]:
## add new column and valuesshould be zero


df['new_col']=1.5
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.5
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.5
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.5
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.5
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.5
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,1.5
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,1.5
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,1.5
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,1.5
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,1.5
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,1.5
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1.5
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,1.5
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,1.5
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,1.5
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,1.5
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,S,1.5
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,1.5
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,1.5
19,20,1,3,"Masselamani, Mr. Charles",male,NaN,0,0,2649,7.2250,NaN,C,1.5

there are two main ways to insert or add a new column to a DataFrame,
If you do not want your new column at the end, use the df.insert() method.

SYNTX- SYNTX- 
df.insert(loc, column_name, value, allow_duplicates=False)

In [43]:
df.insert(loc =3,column='Food',value=0)
df

,PassengerId,Survived,Pclass,Food,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.5
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.5
2,3,1,3,0,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.5
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.5
4,5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.5
5,6,0,3,0,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,1.5
6,7,0,1,0,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,1.5
7,8,0,3,0,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,1.5
8,9,1,3,0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,1.5
9,10,1,2,0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,1.5
10,11,1,3,0,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,1.5
11,12,1,1,0,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1.5
12,13,0,3,0,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,1.5
13,14,0,3,0,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,1.5
14,15,0,3,0,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,1.5
15,16,1,2,0,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,1.5
16,17,0,3,0,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,S,1.5
17,18,1,2,0,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,1.5
18,19,0,3,0,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,1.5
19,20,1,3,0,"Masselamani, Mr. Charles",male,NaN,0,0,2649,7.2250,NaN,C,1.5

In [50]:
df.drop("Food", axis =1, inplace = True)

In [51]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.5
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.5
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.5
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.5
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.5
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,1.5
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,1.5
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,1.5
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,1.5
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,1.5
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,1.5
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1.5
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,1.5
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,1.5
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,1.5
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,1.5
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,S,1.5
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,1.5
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,1.5
19,20,1,3,"Masselamani, Mr. Charles",male,NaN,0,0,2649,7.2250,NaN,C,1.5

In [53]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselamani, Mr. Charles",male,NaN,0,0,2649,7.2250,NaN,C

In [54]:
# Handling missing values

df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,True,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,False,False,False,True,False
15,False,False,False,False,False,False,False,False,False,False,True,False
16,False,False,False,False,False,False,False,False,False,False,True,False
17,False,False,False,False,False,True,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,True,False
19,False,False,False,False,False,True,False,False,False,False,True,False

In [56]:
df.isnull().any(axis=1)

0      True
1     False
2      True
3     False
4      True
5      True
6     False
7      True
8      True
9      True
10    False
11    False
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
dtype: bool

In [57]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked       False
dtype: bool

In [58]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age             3
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          15
Embarked        0
dtype: int64

In [60]:
df_filled =df.fillna(0)